# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_auto_20181106_1154'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtypes',
            table='axf_foodtypes',
        ),
    ]
